### ISSUE TITLE
PXD019123, KeyError: 'trFE_BOVIN'

### ISSUE THREAD

**Issue by asierlarrea** [bigbio/ibaqpy#13]
PXD019123, KeyError: 'trFE_BOVIN' when running compute_ibaqpy

**Comment by WangHong007** [comment]
@asierlarrea Are you using the correct library of protein sequences? Find the fasta file used in the `pipeline_info/pipeline_report.txt `file in each project. Common databases are here: https://github.com/multiomics/multiomics-configs/tree/master/databases

**Comment by asierlarrea** [comment]
@WangHong007 Sorry, you are right. We have fixed this problem, but I forgot to close the issue. Now we are working with Homo-sapiens-uniprot-reviewed-contaminants-decoy-202210.fasta and it works correctly. thanks!
