### ISSUE TITLE
Move pandas to polars for better performance

### ISSUE THREAD

**Issue by ypriverol** [bigbio/ibaqpy#18]
We have a set of large-scale datasets: 
`40'719'166 PXD017052-DIA-features.tsv`

When you have more than `40M` features. The current normalization tool needs more than 900GB for loading the Matrix. @timosachsenberg suggested in some of our python tools to use the Polars library (https://pola-rs.github.io/polars/py-polars/html/reference/index.html)

**Comment by jpfeuffer** [comment]
:rocket:

**Comment by ypriverol** [comment]
We are using parquet an and stream API which looks really nice now and we can compute on really large datasets.
